### ISSUE TITLE
libressl support

### ISSUE THREAD

**Issue by Gillingham** [python-ldap/python-ldap#223]
Inquiring to see if http://www.libressl.org/ support is planned, or would be considered.

Currently python-ldap fails to connect to TLS based LDAP servers on anything based on alpinelinux > 3.4, since it has replaced openssl with libressl for python and libldap.
This affects a growing number of official Docker images, since alpine 3.4 is now EOL'd and official images have started the updates to the current release (3.7)

---

Issue description:

python-ldap fails to connect to TLS based ldap servers when linked against libressl

Steps to reproduce: 

```
$ docker run --rm -ti python:3-alpine sh
# apk update && apk add python py-pip libldap ca-certificates build-base python-dev openldap-dev
# pip install python-ldap
# python
>>> import ldap
ldap.set_option(ldap.OPT_DEBUG_LEVEL, 255)
l = ldap.initialize('ldaps://ldap')
l.simple_bind_s('','')
```

Results in:
```
ldap_pvt_connect: fd: 3 tm: -1 async: 0
attempting to connect:
connect success
TLS trace: SSL_connect:before/connect initialization
TLS trace: SSL_connect:SSLv3 write client hello A
TLS trace: SSL_connect:failed in SSLv3 read server hello A
TLS: can't connect: .
ldap_err2string
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/ldap/ldapobject.py", line 443, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/usr/local/lib/python3.6/site-packages/ldap/ldapobject.py", line 437, in simple_bind
    return self._ldap_call(self._l.simple_bind,who,cred,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/usr/local/lib/python3.6/site-packages/ldap/ldapobject.py", line 329, in _ldap_call
    reraise(exc_type, exc_value, exc_traceback)
  File "/usr/local/lib/python3.6/site-packages/ldap/compat.py", line 44, in reraise
    raise exc_value
  File "/usr/local/lib/python3.6/site-packages/ldap/ldapobject.py", line 313, in _ldap_call
    result = func(*args,**kwargs)
ldap.SERVER_DOWN: {'desc': "Can't contact LDAP server"}
```

Additional Information:
```
# ldd /usr/local/lib/python3.6/site-packages/_ldap.cpython-36m-x86_64-linux-gnu.so
	ldd (0x7f6f10a03000)
	libldap_r-2.4.so.2 => /usr/lib/libldap_r-2.4.so.2 (0x7f6f105ad000)
	liblber-2.4.so.2 => /usr/lib/liblber-2.4.so.2 (0x7f6f103a0000)
	libpython3.6m.so.1.0 => /usr/local/lib/libpython3.6m.so.1.0 (0x7f6f0fe68000)
	libc.musl-x86_64.so.1 => ldd (0x7f6f10a03000)
	libsasl2.so.3 => /usr/lib/libsasl2.so.3 (0x7f6f0fc4f000)
	libssl.so.44 => /lib/libssl.so.44 (0x7f6f0fa03000)
	libcrypto.so.42 => /lib/libcrypto.so.42 (0x7f6f0f65d000)
# apk info --who-owns /lib/libssl.so.44
/lib/libssl.so.44 is owned by libressl2.6-libssl-2.6.4-r2
# apk info --who-owns /lib/libcrypto.so.42
/lib/libcrypto.so.42 is owned by libressl2.6-libcrypto-2.6.4-r2
```

Operating system: Alpine Linux >3.4

Python version: 3.6.5 (and prior)

python-ldap version: All

**Comment by encukou** [comment]
> Inquiring to see if http://www.libressl.org/ support is planned, or would be considered.

Yes, someone just needs to write the implementation. And tests (though this probably wouldn't need more testing than running the existing test suite in Docker).

**Comment by tiran** [comment]
This looks like an issue with OpenLDAP client libraries and LibreSSL, not python-ldap. The python-ldap package just uses whatever TLS/SSL library is compiled into ``libldap_r``. In your case, ldap is connecting to a server with SSLv3, but LibreSSL has SSLv3 support removed.

Try to set the minimal protocol version to TLS 1.0 (0x301):

```
>>> import ldap
>>> ldap.set_option(ldap.OPT_DEBUG_LEVEL, 255)                          
>>> conn = ldap.initialize('ldaps://HOST')
ldap_create
ldap_url_parse_ext(ldaps://HOST)
>>> conn.set_option(ldap.OPT_X_TLS_PROTOCOL_MIN, 0x301)
>>> conn.set_option(ldap.OPT_X_TLS_NEWCTX, 0)
>>> conn.simple_bind_s('', '')
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP HOST:636
ldap_new_socket: 3
ldap_prepare_socket: 3
ldap_connect_to_host: Trying 10.37.171.129:636
ldap_pvt_connect: fd: 3 tm: -1 async: 0
attempting to connect: 
connect success
TLS: info: SSL supported protocol version range is (0x301, 0x304) (SSL_VersionRangeGetSupported).
TLS: info: SSL default protocol version range is (0x301, 0x303) (SSL_VersionRangeGetDefault).
TLS: info: TLS configured protocol minimal version is 0x301, the maximal version (the NSS default) is 0x303.
TLS: info: SSL set protocol version range is (0x301, 0x303) (SSL_VersionRangeGet).
...
```

**Comment by tiran** [comment]
I cannot reproduce the issue on Alpine. A LDAPS connection to Debian's LDAP server works fine for me. Maybe it's a problem with your LDAP server? LibreSSL has disabled old SSL versions and bad cipher suites by default.

```
/ # python
Python 3.6.5 (default, Jun  6 2018, 23:08:29) 
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldap
>>> ldap.set_option(ldap.OPT_DEBUG_LEVEL, 255)                                 
>>> c = ldap.initialize('ldaps://db.debian.org')
ldap_create
ldap_url_parse_ext(ldaps://db.debian.org)
>>> c.simple_bind('', '')
ldap_sasl_bind
ldap_send_initial_request
ldap_new_connection 1 1 0
ldap_int_open_connection
ldap_connect_to_host: TCP db.debian.org:636
ldap_new_socket: 3
ldap_prepare_socket: 3
ldap_connect_to_host: Trying 82.195.75.106:636
ldap_pvt_connect: fd: 3 tm: -1 async: 0
attempting to connect: 
connect success
TLS trace: SSL_connect:before/connect initialization
TLS trace: SSL_connect:SSLv3 write client hello A
TLS trace: SSL_connect:SSLv3 read server hello A
TLS certificate verification: depth: 2, err: 0, subject: /O=Digital Signature Trust Co./CN=DST Root CA X3, issuer: /O=Digital Signature Trust Co./CN=DST Root CA X3
TLS certificate verification: depth: 1, err: 0, subject: /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3, issuer: /O=Digital Signature Trust Co./CN=DST Root CA X3
TLS certificate verification: depth: 0, err: 0, subject: /CN=db.debian.org, issuer: /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
TLS trace: SSL_connect:SSLv3 read server certificate A
TLS trace: SSL_connect:SSLv3 read server key exchange A
TLS trace: SSL_connect:SSLv3 read server certificate request A
TLS trace: SSL_connect:SSLv3 read server done A
TLS trace: SSL_connect:SSLv3 write client certificate A
TLS trace: SSL_connect:SSLv3 write client key exchange A
TLS trace: SSL_connect:SSLv3 write change cipher spec A
TLS trace: SSL_connect:SSLv3 write finished A
TLS trace: SSL_connect:SSLv3 flush data
TLS trace: SSL_connect:SSLv3 read finished A
ldap_open_defconn: successful
ldap_send_server_request
1
```

**Comment by Gillingham** [comment]
Is there a way to have either library display more information about the failure to connect, as it is now I've tried setting MIN_VERSION to 0x301 up to 0x303 no to avail.

**Comment by tiran** [comment]
All logging is handled by ``libldap`` internally. We have no influence other than setting the logging level. I suggest that you check your LDAP server logs and use Wireshark / tcpdump to inspect the TLS/SSL handshake.

All of TLS/SSL is handled by ``libldap`` internally. python-ldap can only set flags. Any issue is more likely a compatibility issue between libldap and LibreSSL.

**Comment by encukou** [comment]
Unfortunately, this doesn't look like something that can be solved in python-ldap.
Please re-open if you disagree or have more information.
