### ISSUE TITLE
'Tuple_to_LDAPMod(): expected a byte string in the list'

### ISSUE THREAD

**Issue by italolemos** [python-ldap/python-ldap#237]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:

Does anyone have faced with this error? 
Basically I got this error when I try to pass an email address using the add_s method. The type of email is a string and I encode it to utf-8
email = 'email@example.com'

        def create_user(self, cpf, name, campus, email):
        """New LDAP User"""

        dn = generate_dn(name, 'TEST', campus)

        attrs = [('objectClass',
                  ['person'.encode('utf-8'), 'organizationalPerson'.encode('utf-8'), 'top'.encode('utf-8'),
                   'user'.encode('utf-8')]),
                 ('cn', [name.encode('utf-8')]),
                 ('objectCategory', ['CN=Person,CN=Schema,CN=Configuration,DC=ifpe,DC=local'.encode('utf-8')]),
                 ('sn', [name.rsplit(' ', 1)[-1].encode('utf-8')]),
                 (settings.LDAP['USERID'], [cpf.encode('utf-8')]),
                 ('mail', [email.encode('utf-8')]),
                 ('givenName', [name.encode('utf-8')]),
                 # ('description', job_title.encode('utf-8')),
                 # ('title', job_title.encode('utf-8')),
                 ('brPersonCPF', cpf.encode('utf-8')),
                 # ('brSiape', str(siape).encode('utf-8')),
                 # ('initials', initials.encode('utf-8')),
                 ('brEduAffiliationType', 'student'),
                 ('brCampus', campus.encode('utf-8'))]

        self.con.add_s(dn, attrs)

`student = Student.objects.get(identifier)`
`create_user(student.identider, student.name, student.campus, student.email`

The error log:
```python
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fe6066320d0>
Traceback (most recent call last):
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 120, in inner_run
    self.check(display_num_errors=True)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/core/management/base.py", line 364, in check
    include_deployment_checks=include_deployment_checks,
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/core/management/base.py", line 351, in _run_checks
    return checks.run_checks(**kwargs)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/core/checks/registry.py", line 73, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/core/checks/urls.py", line 13, in check_url_config
    return check_resolver(resolver)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/core/checks/urls.py", line 23, in check_resolver
    return check_method()
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/urls/resolvers.py", line 397, in check
    for pattern in self.url_patterns:
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/urls/resolvers.py", line 536, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/utils/functional.py", line 36, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/urls/resolvers.py", line 529, in urlconf_module
    return import_module(self.urlconf_name)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/italolemos/PycharmProjects/gerador_de_email/gerador_de_email/urls.py", line 22, in <module>
    path('', include('core.urls', namespace='core')),
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/django/urls/conf.py", line 34, in include
    urlconf_module = import_module(urlconf_module)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/italolemos/PycharmProjects/gerador_de_email/core/urls.py", line 3, in <module>
    from .views import upload_spreadsheet, StudentListView, index, IndexPageView, student_create_email, confirm_data
  File "/home/italolemos/PycharmProjects/gerador_de_email/core/views.py", line 15, in <module>
    from .services import read_spreadsheet, create_email, student_exists, approve_information
  File "/home/italolemos/PycharmProjects/gerador_de_email/core/services.py", line 10, in <module>
    from .ldap import LdapConnection
  File "/home/italolemos/PycharmProjects/gerador_de_email/core/ldap.py", line 66, in <module>
    email=student.email
  File "/home/italolemos/PycharmProjects/gerador_de_email/core/ldap.py", line 57, in create_user
    self.con.add_s(dn, attrs)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/ldap/ldapobject.py", line 428, in add_s
    return self.add_ext_s(dn,modlist,None,None)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/ldap/ldapobject.py", line 413, in add_ext_s
    msgid = self.add_ext(dn,modlist,serverctrls,clientctrls)
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/ldap/ldapobject.py", line 410, in add_ext
    return self._ldap_call(self._l.add_ext,dn,modlist,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls))
  File "/home/italolemos/PycharmProjects/gerador_de_email/venv2/bin/python/lib/python3.6/site-packages/ldap/ldapobject.py", line 313, in _ldap_call
    result = func(*args,**kwargs)
TypeError: ('Tuple_to_LDAPMod(): expected a byte string in the list', 's')

```
             

Even encoding the email variable I got error
 

EDIT: I wrote my entire function and put error log
Steps to reproduce: 

Operating system: 
Manjaro  Linux 17.1.11

Python version: 
3.6.5
python-ldap version: 
3.1.0

**Comment by tiran** [comment]
It's hard to say what is going wrong. Please post a full example with a complete traceback.

**Comment by italolemos** [comment]
@tiran Edited with more information

**Comment by encukou** [comment]
@italolemos, Does that solve the issue?

**Comment by italolemos** [comment]
> @italolemos, Does that solve the issue?

Yeah, I solved. It's just put the "[ ]" to be a list.

**Comment by zypro** [comment]
> You have to provide all attributes as list of byte strings. Instead of
> 
> ```
> ('brEduAffiliationType', 'student'),
> ('brCampus', campus.encode('utf-8')),
> ```
> 
> do
> 
> ```
> ('brEduAffiliationType', [b'student']),
> ('brCampus', [campus.encode('utf-8')]),
> ```

If I'm doing so, the package writes `b'my string'` into the ldap... Why does it deliver the `b''` too?

**Comment by 4devs-net-br** [comment]
https://4devs.net.br/gerador-cpf
