### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by Xk0nSid** [python-ldap/python-ldap#254]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:

I am trying to add a user to pre-existing LDAP group and I'm getting `TypeError`.

```
Traceback (most recent call last):
  File "add_user_lgroup.py", line 74, in <module>
    main()
  File "add_user_lgroup.py", line 70, in main
    add_user_to_group(ldap_conn, options.group_dn, options.user_dn)
  File "add_user_lgroup.py", line 47, in add_user_to_group
    [user_dn],
  File "/home/sid/workspace/python/ldap_add_user/venv/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 629, in modify_s
    return self.modify_ext_s(dn,modlist,None,None)
  File "/home/sid/workspace/python/ldap_add_user/venv/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 601, in modify_ext_s
    msgid = self.modify_ext(dn,modlist,serverctrls,clientctrls)
  File "/home/sid/workspace/python/ldap_add_user/venv/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 597, in modify_ext
    modlist = self._bytesify_modlist('modlist', modlist, with_opcode=True)
  File "/home/sid/workspace/python/ldap_add_user/venv/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 194, in _bytesify_modlist
    for op, attr, val in modlist
  File "/home/sid/workspace/python/ldap_add_user/venv/local/lib/python2.7/site-packages/ldap/ldapobject.py", line 193, in <genexpr>
    (op, self._bytesify_input(arg_name, attr), val)
TypeError: 'int' object is not iterable
```

Steps to reproduce: 

```python
    ldap_conn = ldap.initialize(
            "ldap://{}".format('127.0.0.1'),
            bytes_mode=False)
    ldap_conn.bytes_strictness = 'warn'
    ldap_conn.simple_bind_s(options.manager, options.password)

    group_dn = "cn=admin,ou=groups,dc=example,dc=com"
    user_dn = "cn=user1,cn=users,ou=groups,dc=example,dc=com"
    ldap_conn.modify_s(group_dn, [
        ldap.MOD_ADD,
        'member',
        [user_dn],
    ])
```

Operating system: Ubuntu 14.04

Python version: 2.7.6

python-ldap version: 3.1.0

**Comment by tiran** [comment]
Are you absolutely sure that your reproducer does reproduce the issue for you? I can't reproduce it. The exception looks like you are passing an int as second member of the mod list, but it's clearly a string in your reproducer.

Please post your ``add_user_to_group`` function.

**Comment by Xk0nSid** [comment]
Here is my add_user_to_group method:

```python
def add_user_to_group(ldap_conn, group_dn, user_dn):
    ldap_conn.modify_s(group_dn, [
        ldap.MOD_ADD,
        'member',
        [user_dn],
    ])
```
I'm using `OptionParser` to get `group_dn` and `user_dn` from command line parameters.

Here's an example invocation:

```sh
$ python add_user_lgroup.py --address '127.0.0.1' --manager 'cn=admin,dc=example,dc=com' -p 'admin_password' -g 'cn=admin,ou=groups,dc=example,dc=com' -u 'cn=user1,cn=users,ou=groups,dc=example,dc=com
```

**Comment by encukou** [comment]
Please re-open if that didn't help.
