### ISSUE TITLE
TypeError in filter_format

### ISSUE THREAD

**Issue by nguyenvpd** [python-ldap/python-ldap#279]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:
```
File "/usr/local/site-packages/ldap/filter.py", line 57, in filter_format
  return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
TypeError: not all arguments converted during string formatting
```

Operating system: 
mac OS Mojave

Version 10.14.3
Python version: 

PyPy3.5 v7.0.0
python-ldap version: 
3.1.0

Solution:
Replace https://github.com/python-ldap/python-ldap/blob/master/Lib/ldap/filter.py#L57
with `return filter_template.format(*map(escape_filter_chars,assertion_values))`

**Comment by tiran** [comment]
Please provide the full traceback. It's impossible to tell what went wrong without a full traceback. A reproducer would be fantastic.

**Comment by nguyenvpd** [comment]
Full traceback:
```
 Traceback (most recent call last):
   File "/opt/ha/apps/flask_app/flask_app/dispatcher.py", line 45, in __call__
     return app(environ, start_response)
   File "/usr/local/site-packages/flask/app.py", line 1994, in __call__
     return self.wsgi_app(environ, start_response)
   File "/usr/local/site-packages/flask/app.py", line 1985, in wsgi_app
     response = self.handle_exception(e)
   File "/usr/local/site-packages/flask/app.py", line 1540, in handle_exception
     reraise(exc_type, exc_value, tb)
   File "/usr/local/site-packages/flask/_compat.py", line 33, in reraise
     raise value
   File "/usr/local/site-packages/flask/app.py", line 1982, in wsgi_app
     response = self.full_dispatch_request()
   File "/usr/local/site-packages/flask/app.py", line 1614, in full_dispatch_request
     rv = self.handle_user_exception(e)
   File "/usr/local/site-packages/flask/app.py", line 1517, in handle_user_exception
     reraise(exc_type, exc_value, tb)
   File "/usr/local/site-packages/flask/_compat.py", line 33, in reraise
     raise value
   File "/usr/local/site-packages/flask/app.py", line 1612, in full_dispatch_request
     rv = self.dispatch_request()
   File "/usr/local/site-packages/flask/app.py", line 1598, in dispatch_request
     return self.view_functions[rule.endpoint](**req.view_args)
   File "/opt/ha/apps/flask_app/flask_app/admin/__init__.py", line 162, in login_post
     groups = ldap.get_user_groups(request.values.get("email", "").strip().lower())
   File "/usr/local/site-packages/flask_simpleldap/__init__.py", line 229, in get_user_groups
     (user,)),
   File "/usr/local/site-packages/ldap/filter.py", line 57, in filter_format
     return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
TypeError: not all arguments converted during string formatting
```
So looks like here: https://github.com/admiralobvious/flask-simpleldap/blob/v1.1.2/flask_simpleldap/__init__.py#L227

To reproduce:
Use that `get_user_groups` function with an email.

**Comment by tiran** [comment]
It looks like a faulty configuration. What's the value of ``LDAP_USER_OBJECT_FILTER`` from your application configuration? It must contain exactly one ``%s``.

**Comment by nguyenvpd** [comment]
We have
```python
LDAP_USER_OBJECT_FILTER = '(&(objectclass=posixAccount)(memberOf=cn=admins=groups,dc=pd,dc=com)(mail={0}))'
```
Looks like we use `{0}` instead of `{s}` 😓

**Comment by tiran** [comment]
Yeah, the function only works with old-style module string formatting. It has to be ``(mail=%s)``.
