### ISSUE TITLE
Doubled class qualifier for IterableUserDict.__init__

### ISSUE THREAD

**Issue by paurkedal** [python-ldap/python-ldap#302]
If you found a bug in python-ldap, or would request a new feature,
this is the place to let us know.

Please describe the issue and your environment here.

---

Issue description:

There is a doubled class qualifier for `IterableUserDict.__init__` in `Lib/ldap/schema/models.py` in `Entry.__init__`.

Steps to reproduce:
```
from ldap.schema.models import Entry; Entry(None, None, {})
```
The two first parameters should be non-null of course, but `Entry.__init__` does not depend on it, and the error is:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/ldap/schema/models.py", line 637, in __init__
    IterableUserDict.IterableUserDict.__init__(self,{})
AttributeError: class IterableUserDict has no attribute 'IterableUserDict'
```

Operating system: 
Ubuntu 18.04

Python version: 
2.7.15+ and 3.6.8

python-ldap version: 
3.0.0-1 (and current master)

**Comment by encukou** [comment]
It looks like schema.models.Entry is unused and untested.
Could you write a few tests for it?

**Comment by paurkedal** [comment]
I can look into that next week, I hope.

OT: In order to continue using this library I will need EPEL packages for Python 3, as my own software is published there, and the next version will be Python 3.  Do you know about packaging for EPEL (and Ubuntu), and whether it makes sense to open an issue here once we've fixed and tested?

**Comment by encukou** [comment]
Not here. Fedora/EPEL packaging lives at https://src.fedoraproject.org/rpms/python-ldap. I don't know about Ubuntu.

**Comment by paurkedal** [comment]
Makes sense.
