### ISSUE TITLE
Core dump on OpenBSD 6.6: "in free(): bogus pointer (double free?)"

### ISSUE THREAD

**Issue by iredmail** [python-ldap/python-ldap#305]
Issue description:  Try to bind to local ldap server, python (both py2 and py3) core dumped.

Steps to reproduce: 

- Setup a working LDAP server. (connection/query from other applications or ldap command line tools works fine.)
- Run below code with correct bind dn and password, error raised while running `bind_s()`:

```
import ldap

uri = 'ldap://127.0.0.1:389'
dn = 'cn=vmail,dc=a,dc=io'
pw = 'f70c8f378fa49c3684b84637d790da37'

conn = ldap.ldapobject.ReconnectLDAPObject(uri)
conn.bind_s(dn, pw)
```

Error message:

```
python2(92014) in free(): bogus pointer (double free?) 0xffffffffffffffff
Abort trap (core dumped) 
```

Operating system: OpenBSD 6.6, amd64 (a guest OS running inside VMware Fusion on macOS 10.15)

Python version: 2.7.16, 3.7.4
python-ldap version: 3.2.0

```
# python2 -c "import ldap; print ldap.__version__"
3.2.0

# python3 -c "import ldap; print(ldap.__version__)"
3.2.0
```

See also:

- OpenBSD manual page: [free](https://man.openbsd.org/free.3#DIAGNOSTICS)

```
“bogus pointer (double free?)”
    An attempt to free() or reallocate an unallocated pointer was made.
```

**Comment by iredmail** [comment]
Backtrace:

```
#0  thrkill () at -:3                                                    [9/892]
#1  0x000001b6116f089e in _libc_abort () at /usr/src/lib/libc/stdlib/abort.c:51 
#2  0x000001b6116c7546 in wrterror (d=Variable "d" is not available.            
)                                                                               
    at /usr/src/lib/libc/stdlib/malloc.c:300                                    
#3  0x000001b6116ca729 in findpool (p=0xffffffffffffffff, argpool=Variable "argp
ool" is not available.                                                          
)                                                                               
    at /usr/src/lib/libc/stdlib/malloc.c:1355                                   
#4  0x000001b6116c785a in ofree (argpool=0x7f7fffff3fe0, p=0xffffffffffffffff,  
    clear=0, check=0, argsz=0) at /usr/src/lib/libc/stdlib/malloc.c:1369
#5  0x000001b6116c7790 in free (ptr=0xffffffffffffffff)                     
    at /usr/src/lib/libc/stdlib/malloc.c:1488                     
#6  0x000001b61f03fae3 in ldap_free_request_int (ld=Variable "ld" is not available.                                                                             
) at request.c:991                      
#7  0x000001b61f02acf5 in ldap_result (ld=Variable "ld" is not available.       
) at result.c:886
#8  0x000001b61f03376e in ldap_sasl_interactive_bind_s (ld=0x1b625560980, 
    dn=0x1b630b5252c "", mechs=0x1b5c903f354 "EXTERNAL", serverControls=0x0, 
    clientControls=0x0, flags=2, 
    interact=0x1b5f14f74b0 <py_ldap_sasl_interaction>, defaults=0x1b5b21be518)
    at sasl.c:537
#9  0x000001b5f14f7d8d in l_ldap_sasl_interactive_bind_s (self=0x1b55a9773c8, 
    args=Variable "args" is not available.
) at Modules/LDAPObject.c:797
#10 0x000001b556257ee2 in PyEval_EvalFrameEx ()
   from /usr/local/lib/libpython2.7.so.0.0
```

**Comment by iredmail** [comment]
Confirmed it's an OpenBSD 6.6 bug and fixed by "002: RELIABILITY FIX":
https://www.openbsd.org/errata66.html
