### ISSUE TITLE
filter_format() unable to process template with single %s

### ISSUE THREAD

**Issue by DoraPaula** [python-ldap/python-ldap#333]
Operating system: Debian bullseye
python-ldap version: https://packages.debian.org/bullseye/python3-ldap

Issue description:

I'm not only an absolute python-ldap-, but also a python-rookie. Thus I don't know whether this issue is caused by a bug or by me (misusing the library). See the following code:

Nevertheless, I would expect the second call to filter_format(...) to replace the single %s.

```
#!/usr/bin/python3

import ldap
import ldapurl

fineLdapUrl = "ldap://ldap.example.com:389/dc=example,dc=com?cn?one?(&(%s=%s)(objectclass=inetOrgPerson))"
url = ldapurl.LDAPUrl(fineLdapUrl)

attrName = "uid"
attrValue = "test"

from ldap.filter import filter_format
print("template with two %s: \"" + url.filterstr + "\" works:")
search_filter = filter_format(url.filterstr, (attrName, attrValue))
print("search_filter: " + search_filter)
print("")

anotherLdapUrl = "ldap://ldap.example.com:389/dc=example,dc=com?cn?one?(&(uid=%s)(objectclass=inetOrgPerson))"
url = ldapurl.LDAPUrl(anotherLdapUrl)
print("template with just one %s: \"" + url.filterstr + "\" does not work:")
search_filter = filter_format(url.filterstr, attrValue)
print("search_filter: " + search_filter)
print("")

exit(0)
```

**Comment by tiran** [comment]
``filter_format()`` requires a tuple as second attribute. You are passing a single value.

Your example:
```
>>> anotherLdapUrl = "ldap://ldap.example.com:389/dc=example,dc=com?cn?one?(&(uid=%s)(objectclass=inetOrgPerson))"
>>> url = ldapurl.LDAPUrl(anotherLdapUrl)
>>> filter_format(url.filterstr, attrValue)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.8/site-packages/ldap/filter.py", line 57, in filter_format
    return filter_template % tuple(escape_filter_chars(v) for v in assertion_values)
TypeError: not all arguments converted during string formatting
```

Correct invocation:
```
>>> filter_format(url.filterstr, (attrValue,))
'(&(uid=test)(objectclass=inetOrgPerson))'
```
