### ISSUE TITLE
coverage downgrade breaks RPM build on Fedora

### ISSUE THREAD

**Issue by tiran** [python-ldap/python-ldap#348]
Related to https://github.com/python-ldap/python-ldap/pull/346

Fedora has coverage 5.0.3

```
+ tox --sitepackages
GLOB sdist-make: /home/heimes/redhat/fedora-rpms/python-ldap/python-ldap-3.3.0b1/setup.py
py38 create: /home/heimes/redhat/fedora-rpms/python-ldap/python-ldap-3.3.0b1/.tox/py38
py38 installdeps: coverage<5.0
WARNING: Discarding $PYTHONPATH from environment, to override specify PYTHONPATH in 'passenv' in your configuration.
ERROR: invocation failed (exit code 1), logfile: /home/heimes/redhat/fedora-rpms/python-ldap/python-ldap-3.3.0b1/.tox/py38/log/py38-1.log
================================== log start ===================================
Looking in indexes: http://host.invalid./
WARNING: The repository located at host.invalid. is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host host.invalid.'.
ERROR: Could not find a version that satisfies the requirement coverage<5.0 (from versions: none)
ERROR: No matching distribution found for coverage<5.0
WARNING: The repository located at host.invalid. is not a trusted or secure host and is being ignored. If this repository is available via HTTPS we recommend you use HTTPS instead, otherwise you may silence this warning and allow it anyway with '--trusted-host host.invalid.'.

=================================== log end ====================================
ERROR: could not install deps [coverage<5.0]; v = InvocationError("/home/heimes/redhat/fedora-rpms/python-ldap/python-ldap-3.3.0b1/.tox/py38/bin/python -m pip install 'coverage<5.0'", 1)
___________________________________ summary ____________________________________
ERROR:   py38: could not install deps [coverage<5.0]; v = InvocationError("/home/heimes/redhat/fedora-rpms/python-ldap/python-ldap-3.3.0b1/.tox/py38/bin/python -m pip install 'coverage<5.0'", 1)
error: Bad exit status from /var/tmp/rpm-tmp.lryxax (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.lryxax (%check)
```

**Comment by tiran** [comment]
Fun fact: I'm getting the same SQLite error when I run ``fedpkg local`` with a patch build:

```
Ran 291 tests in 30.479s

OK (skipped=53, expected failures=3)
Traceback (most recent call last):
  File "/usr/lib64/python3.8/site-packages/coverage/cmdline.py", line 703, in do_run
    runner.run()
  File "/usr/lib64/python3.8/site-packages/coverage/execfile.py", line 247, in run
    exec(code, main_mod.__dict__)
  File "/usr/lib64/python3.8/unittest/__main__.py", line 18, in <module>
    main(module=None)
  File "/usr/lib64/python3.8/unittest/main.py", line 101, in __init__
    self.runTests()
  File "/usr/lib64/python3.8/unittest/main.py", line 273, in runTests
    sys.exit(not self.result.wasSuccessful())
SystemExit: False

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib64/python3.8/site-packages/coverage/__main__.py", line 8, in <module>
    sys.exit(main())
  File "/usr/lib64/python3.8/site-packages/coverage/cmdline.py", line 828, in main
    status = CoverageScript().command_line(argv)
  File "/usr/lib64/python3.8/site-packages/coverage/cmdline.py", line 555, in command_line
    return self.do_run(options, args)
  File "/usr/lib64/python3.8/site-packages/coverage/cmdline.py", line 710, in do_run
    self.coverage.save()
  File "/usr/lib64/python3.8/site-packages/coverage/control.py", line 642, in save
    data = self.get_data()
  File "/usr/lib64/python3.8/site-packages/coverage/control.py", line 696, in get_data
    if self._collector and self._collector.flush_data():
  File "/usr/lib64/python3.8/site-packages/coverage/collector.py", line 423, in flush_data
    self.covdata.add_arcs(self.mapped_file_dict(self.data))
  File "/usr/lib64/python3.8/site-packages/coverage/sqldata.py", line 477, in add_arcs
    con.executemany(
  File "/usr/lib64/python3.8/site-packages/coverage/sqldata.py", line 1033, in __exit__
    self.con.__exit__(exc_type, exc_value, traceback)
sqlite3.OperationalError: disk I/O error
ERROR: InvocationError for command /home/heimes/redhat/fedora-rpms/python-ldap/python-ldap-3.3.0b1/.tox/py38/bin/python -bb -Wignore -m coverage run --parallel -m unittest discover -v -s Tests -p 't_*' (exited with code 1)
```

**Comment by tiran** [comment]
I'm not at a point where I'm considering to remove coverage complete. codecov is not giving meaning information any more and coverage is breaking tests.
