### ISSUE TITLE
Fatal Python error: saving thread twice?

### ISSUE THREAD

**Issue by spaceone** [python-ldap/python-ldap#394]
I receive a crash (SIG_ABORT) with Python 3.7 (Python 2.7 works fine):
```
Fatal Python error: saving thread twice?
Fatal Python error:PyEval_RestoreThread: NULL tstate"
```

MainThread:
```
Thread 0x00007ffff79ba740 (most recent call first):                                                                                                                                                                
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 313 in _ldap_call                                                                                                                                 
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 908 in whoami_s                                                                                                                                   
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1197 in _apply_method_s
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1262 in whoami_s

#0  futex_abstimed_wait_cancelable (private=0, abstime=0x7fffffff9d50, expected=0, futex_word=0x8a3be4 <_PyRuntime+1252>) at ../sysdeps/unix/sysv/linux/futex-internal.h:205
#1  __pthread_cond_wait_common (abstime=0x7fffffff9d50, mutex=0x8a3be8 <_PyRuntime+1256>, cond=0x8a3bb8 <_PyRuntime+1208>) at pthread_cond_wait.c:539
#2  __pthread_cond_timedwait (cond=0x8a3bb8 <_PyRuntime+1208>, mutex=0x8a3be8 <_PyRuntime+1256>, abstime=0x7fffffff9d50) at pthread_cond_wait.c:667
#3  0x00000000005416d5 in PyCOND_TIMEDWAIT (cond=<optimized out>, mut=<optimized out>, us=5000) at ../Python/condvar.h:79
#4  take_gil (tstate=0x8ca160) at ../Python/ceval_gil.h:208
#5  0x00000000005419f3 in PyEval_RestoreThread (tstate=<optimized out>, tstate=<optimized out>) at ../Python/ceval.c:271
#6  0x00007ffff73905a4 in l_ldap_whoami_s (self=0x7fffee2aadf0, args=<optimized out>) at Modules/LDAPObject.c:1337
#7  0x00000000005cd45b in cfunction_call_varargs (kwargs=<optimized out>, args=<optimized out>, func=<built-in method whoami_s of LDAP object at remote 0x7fffee2aadf0>) at ../Objects/call.c:768
#8  PyCFunction_Call (func=<built-in method whoami_s of LDAP object at remote 0x7fffee2aadf0>, args=<optimized out>, kwargs=<optimized out>) at ../Objects/call.c:784
#9  0x000000000054775f in do_call_core (kwdict={}, callargs=(None, None), func=<built-in method whoami_s of LDAP object at remote 0x7fffee2aadf0>) at ../Python/ceval.c:4641
#10 _PyEval_EvalFrameDefault (f=<optimized out>, throwflag=<optimized out>) at ../Python/ceval.c:3191

```

Some other thread:
```
Current thread 0x00007fffed1c4700 (most recent call first):                                                                                                                                                        
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 313 in _ldap_call                                                                                                                                 
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 756 in result4                                                                                                                                    
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 749 in result3                                                                                                                                    
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 742 in result2                                                                                                                                    
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 738 in result                                                                                                                                     
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 846 in search_ext_s      
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1197 in _apply_method_s                                                                                                                           
  File "/usr/lib/python3/dist-packages/ldap/ldapobject.py", line 1259 in search_ext_s  

#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007ffff79df535 in __GI_abort () at abort.c:79
#2  0x00000000004740c5 in fatal_error (prefix=prefix@entry=0x0, msg=msg@entry=0x7ffff7398022 "saving thread twice?", status=status@entry=-1) at ../Python/pylifecycle.c:2179
#3  0x0000000000474139 in Py_FatalError (msg=msg@entry=0x7ffff7398022 "saving thread twice?") at ../Python/pylifecycle.c:2189
#4  0x00007ffff7390d10 in l_ldap_result4 (self=0x7fffee2aadf0, args=<optimized out>) at Modules/LDAPObject.c:1107
#5  0x00000000005cd45b in cfunction_call_varargs (kwargs=<optimized out>, args=<optimized out>, func=<built-in method result4 of LDAP object at remote 0x7fffee2aadf0>) at ../Objects/call.c:768
#6  PyCFunction_Call (func=<built-in method result4 of LDAP object at remote 0x7fffee2aadf0>, args=<optimized out>, kwargs=<optimized out>) at ../Objects/call.c:784
#7  0x000000000054775f in do_call_core (kwdict={}, callargs=(327, 1, -1, 0, 0, 0), func=<built-in method result4 of LDAP object at remote 0x7fffee2aadf0>) at ../Python/ceval.c:4641

```

Steps to reproduce: 
```
import ldap
from concurrent.futures import ThreadPoolExecutor

pool = ThreadPoolExecutor(max_workers=1)
lo = ldap.initialize(LDAP_URI)
lo.start_tls_s()
lo.simple_bind_s(userdn, password)

def search():
    while True:
        lo.search_ext_s(ldap_base, ldap.SCOPE_BASE, '(objectClass=*)')


pool.submit(search)
while True:
    lo.whoami_s()
```

Operating system: 
(debian buster) `Linux master3 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux`
Python version: 
```
Python 3.7.3 (default, Jul 25 2020, 13:03:44) 
[GCC 8.3.0] on linux
```
python-ldap version: 
`3.1.0` (`python3-ldap:amd64 3.1.0-2`)

**Comment by tiran** [comment]
Please upgrade to 3.3.1. The issue has been fixed in https://github.com/python-ldap/python-ldap/issues/289

**Comment by spaceone** [comment]
Thanks. https://github.com/python-ldap/python-ldap/commit/95e1d1a8aa9e6aa036f085af1ace3c295e78412b.patch
