### ISSUE TITLE
python-ldap | pip installation not working

### ISSUE THREAD

**Issue by Alejandrocruz9608** [python-ldap/python-ldap#425]
pip install ldap
Collecting ldap
  Using cached ldap-2.0.0.404.tar.gz (2.0 kB)
Building wheels for collected packages: ldap
  Building wheel for ldap (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\users\ale\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] 
= '"'"'C:\\Users\\ale\\AppData\\Local\\Temp\\pip-install-t6dbdetz\\ldap_99be0d46c19a48be86bc5169bd89b265\\setup.py'"'"'; __file__='"'"'C:\\Users\\ale\\AppData\\Local\\Temp\\pip-install-t6dbdetz\\ldap_99be0d46c19a48be86bc5169bd89b265\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ale\AppData\Local\Temp\pip-wheel-1marva1d'
       cwd: C:\Users\ale\AppData\Local\Temp\pip-install-t6dbdetz\ldap_99be0d46c19a48be86bc5169bd89b265\
  Complete output (84 lines):
  running bdist_wheel
  running build
  running build_py
  ------------------------------------------------------------------------
  # `ldap` on PyPI

  This dummy project is not installable.
  You probably want `python-ldap` instead.

  ### python-ldap

  The widely used [python-ldap](https://python-ldap.org) project provides
  an importable module named `ldap`.

  This goes against the convention that PyPI distribution names should
  match the module names.
  But, python-ldap pre-dates wide use of that convention, and the issue
  is hard to fix now.

  Please install `python-ldap` to get the LDAP bindings.

  ### ldap 1.0

  The `ldap` name on PyPI was used for an unrelated collection of
  LDAP-related utilities, which is not as popular, and confused users who
  install `ldap` to get the `ldap` module.

  The project is no longer developed.
  It is archived as `1.0.x` releases on PyPI, and on
  [GitHub](https://github.com/andreif/ldap).

  ## Why we don't fix this transparently

  This could have been a placeholder  package that depends on `python-ldap`,
  saving you the trouble of reading this message.

  However, `pip` [has trouble](https://github.com/pypa/pip/issues/4961)
  with differently-named packages that provide the same module.

  ## Please: Don't install packages blindly

  When you see the exception:

  ```
  ModuleNotFoundError: No module named 'foo'
  ```

  â€¦ please research the actual requirements instead of going directly for
  `pip install foo`.
  The project (distribution) name may differ from the module(s) it
  provides.

  ------------------------------------------------------------------------
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ale\AppData\Local\Temp\pip-install-t6dbdetz\ldap_99be0d46c19a48be86bc5169bd89b265\setup.py", line 23, in <module>      
      setup(
    File "c:\users\ale\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\ale\appdata\local\programs\python\python39\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "C:\Users\ale\AppData\Local\Temp\pip-install-t6dbdetz\ldap_99be0d46c19a48be86bc5169bd89b265\setup.py", line 18, in run
      raise ValueError(
  ValueError: "ldap" is not installable. You probably want python-ldap.
  ----------------------------------------
  ERROR: Failed building wheel for ldap
  Running setup.py clean for ldap
Failed to build ldap
Installing collected packages: ldap
    Running setup.py install for ldap ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\users\ale\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ale\\AppData\\Local\\Temp\\pip-install-t6dbdetz\\ldap_99be0d46c19a48be86bc5169bd89b265\\setup.py'"'"'; __file__='"'"'C:\\Users\\ale\\AppData\\Local\\Temp\\pip-install-t6dbdetz\\ldap_99be0d46c19a48be86bc5169bd89b265\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ale\AppData\Local\Temp\pip-record-tp_t7a2t\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ale\appdata\local\programs\python\python39\Include\ldap'
         cwd: C:\Users\ale\AppData\Local\Temp\pip-install-t6dbdetz\ldap_99be0d46c19a48be86bc5169bd89b265\
    Complete output (86 lines):
    running install
    running build
    running build_py
    ------------------------------------------------------------------------
    # `ldap` on PyPI

    This dummy project is not installable.
    You probably want `python-ldap` instead.

    ### python-ldap

    The widely used [python-ldap](https://python-ldap.org) project provides
    an importable module named `ldap`.

    This goes against the convention that PyPI distribution names should
    match the module names.
    But, python-ldap pre-dates wide use of that convention, and the issue
    is hard to fix now.

    Please install `python-ldap` to get the LDAP bindings.

    ### ldap 1.0

    The `ldap` name on PyPI was used for an unrelated collection of
    LDAP-related utilities, which is not as popular, and confused users who
    install `ldap` to get the `ldap` module.

    The project is no longer developed.
    It is archived as `1.0.x` releases on PyPI, and on
    [GitHub](https://github.com/andreif/ldap).

    ## Why we don't fix this transparently

    This could have been a placeholder  package that depends on `python-ldap`,
    saving you the trouble of reading this message.

    However, `pip` [has trouble](https://github.com/pypa/pip/issues/4961)
    with differently-named packages that provide the same module.

    ## Please: Don't install packages blindly

    When you see the exception:

    ```
    ModuleNotFoundError: No module named 'foo'
    ```

    â€¦ please research the actual requirements instead of going directly for
    `pip install foo`.
    The project (distribution) name may differ from the module(s) it
    provides.

    ------------------------------------------------------------------------
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ale\AppData\Local\Temp\pip-install-t6dbdetz\ldap_99be0d46c19a48be86bc5169bd89b265\setup.py", line 23, in <module>    
        setup(
      File "c:\users\ale\appdata\local\programs\python\python39\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\ale\appdata\local\programs\python\python39\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\command\install.py", line 546, in run
        self.run_command('build')
      File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\users\ale\appdata\local\programs\python\python39\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "C:\Users\ale\AppData\Local\Temp\pip-install-t6dbdetz\ldap_99be0d46c19a48be86bc5169bd89b265\setup.py", line 18, in run
        raise ValueError(
    ValueError: "ldap" is not installable. You probably want python-ldap.
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'c:\users\ale\appdata\local\programs\python\python39\python.exe' -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ale\\AppData\\Local\\Temp\\pip-install-t6dbdetz\\ldap_99be0d46c19a48be86bc5169bd89b265\\setup.py'"'"'; __file__='"'"'C:\\Users\\ale\\AppData\\Local\\Temp\\pip-install-t6dbdetz\\ldap_99be0d46c19a48be86bc5169bd89b265\\setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ale\AppData\Local\Temp\pip-record-tp_t7a2t\install-record.txt' --single-version-externally-managed --compile --install-headers 'c:\users\ale\appdata\local\programs\python\python39\Include\ldap' Check the logs for full command output.

**Comment by encukou** [comment]
Have you read the output?

To install `python-ldap` (not `ldap`), please see the [installation instructions](https://www.python-ldap.org/en/python-ldap-3.3.0/installing.html) in the documentation. Note especially that you need to have build prerequisites already installed.
