### ISSUE TITLE
getting or setting ldap.OPT_X_SASL_* options raises "ValueError: option error"

### ISSUE THREAD

**Issue by jayhendren** [python-ldap/python-ldap#468]
Issue description:

A ValueError is raised whenever using `get_option` or `set_option` with any `OPT_X_SASL_` options (other, non-SASL options seem to work fine).

Steps to reproduce: 

```
┌─[jay@eagle] - [~/Work/git/systems] - [2022-04-12 03:58:58]
└─[0] <git:(master cb7fb8cae✈) > python
Python 3.8.2 (default, Dec 15 2021, 14:32:00) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ldap
>>> ldap.get_option(ldap.OPT_X_SASL_SECPROPS)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jay/.pyenv/versions/3.8.2/lib/python3.8/site-packages/ldap/functions.py", line 103, in get_option
    return _ldap_function_call(None,_ldap.get_option,option)
  File "/home/jay/.pyenv/versions/3.8.2/lib/python3.8/site-packages/ldap/functions.py", line 52, in _ldap_function_call
    result = func(*args,**kwargs)
ValueError: option error
```

Operating system:  Pop!_OS 20.04 LTS

Python version: 3.8.2 (installed via pyenv)

python-ldap version: 3.4.0

FWIW, I also have the following packages installed:
```
┌─[jay@eagle] - [~/Work/git/systems] - [2022-04-12 04:14:03]
└─[0] <git:(master cb7fb8cae✈) > dpkg -l | grep -iE 'sasl|ldap'
ii  ldap-utils                                       2.4.49+dfsg-2ubuntu1.8                                 amd64        OpenLDAP utilities
ii  libauthen-sasl-perl                              2.1600-1                                               all          Authen::SASL - SASL Authentication framework
ii  libldap-2.4-2:amd64                              2.4.49+dfsg-2ubuntu1.8                                 amd64        OpenLDAP libraries
ii  libldap-common                                   2.4.49+dfsg-2ubuntu1.8                                 all          OpenLDAP common files for libraries
ii  libldap2-dev:amd64                               2.4.49+dfsg-2ubuntu1.8                                 amd64        OpenLDAP development libraries
ii  libldb2:amd64                                    2:2.2.3-0ubuntu0.20.04.2                               amd64        LDAP-like embedded database - shared library
ii  libsasl2-2:amd64                                 2.1.27+dfsg-2ubuntu0.1                                 amd64        Cyrus SASL - authentication abstraction library
ii  libsasl2-dev                                     2.1.27+dfsg-2ubuntu0.1                                 amd64        Cyrus SASL - development files for authentication abstraction library
ii  libsasl2-modules:amd64                           2.1.27+dfsg-2ubuntu0.1                                 amd64        Cyrus SASL - pluggable authentication modules
ii  libsasl2-modules-db:amd64                        2.1.27+dfsg-2ubuntu0.1                                 amd64        Cyrus SASL - pluggable authentication modules (DB)
ii  libsasl2-modules-gssapi-mit:amd64                2.1.27+dfsg-2ubuntu0.1                                 amd64        Cyrus SASL - pluggable authentication modules (GSSAPI)
ii  libsasl2-modules-ldap:amd64                      2.1.27+dfsg-2ubuntu0.1                                 amd64        Cyrus SASL - pluggable authentication modules (LDAP)
```

**Comment by jayhendren** [comment]
Sorry I accidentally hit "enter" while typing the title and that caused the issue to submit.  Editing now...

**Comment by jayhendren** [comment]
I also tested this on RHEL 8.5 (Python 3.8.2, python-ldap 3.4.0), and I'm seeing the same issue there as well.

**Comment by mistotebe** [comment]
Thanks for the report, could you report this against libldap documentation at https://bugs.openldap.org/?

**Comment by jayhendren** [comment]
Done: https://bugs.openldap.org/show_bug.cgi?id=9824
