### ISSUE TITLE
AttributeError: 'LDAP' object has no attribute 'sasl_interactive_bind_s'

### ISSUE THREAD

**Issue by imjoel** [python-ldap/python-ldap#477]
Issue description: Error when calling SASL bind

```
In [9]: conn.sasl_interactive_bind_s('', auth)
Traceback (most recent call last):
  File "C:\Users\joel\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 3437, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-ab0440845da0>", line 1, in <module>
    conn.sasl_interactive_bind_s('', auth)
  File "C:\Users\joel\Anaconda3\lib\site-packages\ldap\ldapobject.py", line 270, in sasl_interactive_bind_s
    return self._ldap_call(self._l.sasl_interactive_bind_s,who,auth,RequestControlTuples(serverctrls),RequestControlTuples(clientctrls),sasl_flags)
AttributeError: 'LDAP' object has no attribute 'sasl_interactive_bind_s'
```

Steps to reproduce: 
Call the sasl_interactive_bind_s function

Sample Code:
```
import ldap
import ldap.sasl

conn = ldap.initialize('ldap://10.0.0.1:389')
auth_tokens = ldap.sasl.digest_md5('xxx@xxx.com.sg', 'pwd')
conn.sasl_interactive_bind_s('', auth_tokens)
```

Operating system: Tested on both Windows 10 and Windows Server 2019 Data center

Python version: 3.8.8

python-ldap version: 3.4.0
*WHL from https://www.lfd.uci.edu/~gohlke/pythonlibs/

Any idea if I'm doing anything wrong?

**Comment by tiran** [comment]
It seems like Windows builds from Christoph Gohlke may not have SASL bindings. It is an optional feature that depends on Cyrus SASL and other libraries.

Please run:

```
import _ldap
print(_ldap.SASL_AVAIL)
```

**Comment by imjoel** [comment]
Seems like you're right, any other known WHL available?

```
import _ldap
print(_ldap.SASL_AVAIL)
0
```
