### ISSUE TITLE
Getting Error while installing the cryptography or firebase admin

### ISSUE THREAD

**Issue by siddharth15o2** [python-ldap/python-ldap#486]
Collecting cryptography==2.8
  Downloading cryptography-2.8.tar.gz (504 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpojqq26sb
       cwd: /tmp/pip-install-lpb2se1w/cryptography_39e6b165e8aa45479c84e220c5e86626
  Complete output (43 lines):
  Traceback (most recent call last):
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
      main()
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 192, in <module>
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 172, in setup
      ok = dist.parse_command_line()
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 479, in parse_command_line
      args = self._parse_command_opts(parser, args)
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 1107, in _parse_command_opts
      nargs = _Distribution._parse_command_opts(self, parser, args)
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 538, in _parse_command_opts
      cmd_class = self.get_command_class(command)
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 954, in get_command_class
      self.cmdclass[command] = cmdclass = ep.load()
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 194, in load
      module = import_module(match.group('module'))
    File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 777, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/command/egg_info.py", line 24, in <module>
      from setuptools.command.sdist import sdist
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/command/sdist.py", line 12, in <module>
      from .build import _ORIGINAL_SUBCOMMANDS
    File "/tmp/pip-build-env-jtz7yneh/overlay/lib/python3.8/site-packages/setuptools/command/build.py", line 9, in <module>
      from typing import Protocol
  ImportError: cannot import name 'Protocol' from 'typing' (/usr/local/lib/python3.8/typing.py)
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/be/60/da377e1bed002716fb2d5d1d1cab720f298cb33ecff7bf7adea72788e4e4/cryptography-2.8.tar.gz#sha256=3cda1f0ed8747339bbdf71b9f38ca74c7b592f24f65cdb3ab3765e4b02871651 (from https://pypi.org/simple/cryptography/) (requires-python:>=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*). Command errored out with exit status 1: /usr/local/bin/python /usr/local/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpojqq26sb Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement cryptography==2.8
ERROR: No matching distribution found for cryptography==2.8
WARNING: You are using pip version 21.0.1; however, version 22.2.2 is available.
You should consider upgrading via the '/usr/local/bin/python -m pip install --upgrade pip' command.

**Comment by tiran** [comment]
You are reporting your build problem to the wrong project. I don't see python-ldap in your traceback. It looks like a problem with PyCA cryptography and setuptools. I suggest that you open an issue with setuptools.
