### ISSUE TITLE
urlfetch from LDAP is broken on Python 2.7

### ISSUE THREAD

**Issue by tiran** [python-ldap/python-ldap#54]
See PR #52 for a reproducer

```
======================================================================
ERROR: test_urlfetch_ldap (Tests.t_ldap_schema_subentry.TestSubschemaUrlfetchSlapd)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/python-ldap/python-ldap/Tests/t_ldap_schema_subentry.py", line 87, in test_urlfetch_ldap
    dn, schema = ldap.schema.urlfetch(self.server.ldap_uri)
  File "/home/travis/build/python-ldap/python-ldap/Lib/ldap/schema/subentry.py", line 462, in urlfetch
    l.simple_bind_s(ldap_url.who or '', ldap_url.cred or '')
  File "/home/travis/build/python-ldap/python-ldap/Lib/ldap/ldapobject.py", line 409, in simple_bind_s
    msgid = self.simple_bind(who,cred,serverctrls,clientctrls)
  File "/home/travis/build/python-ldap/python-ldap/Lib/ldap/ldapobject.py", line 402, in simple_bind
    who, cred = self._bytesify_inputs(who, cred)
  File "/home/travis/build/python-ldap/python-ldap/Lib/ldap/ldapobject.py", line 147, in <genexpr>
    for value in values
  File "/home/travis/build/python-ldap/python-ldap/Lib/ldap/ldapobject.py", line 131, in _bytesify_input
    raise TypeError("All provided fields *must* be text when bytes mode is off; got %r" % (value,))
TypeError: All provided fields *must* be text when bytes mode is off; got ''
```

**Comment by tiran** [comment]
Fixed in #52
