### ISSUE TITLE
[doc] Explain TLS/SSL gotchas

### ISSUE THREAD

**Issue by tiran** [python-ldap/python-ldap#55]
TLS/SSL and X.509 are tricky. OpenLDAP adds some additional gotchas to the stack. We should document them so users don't run into issues like https://github.com/pyldap/pyldap/issues/53

* ``start_tls_s()`` requires protocol version 3. It does not work with protocol version 2.
* Several, perhaps all ``set_option(OPT_X_TLS_*, ...)`` calls require a final ``set_option(ldap.OPT_X_TLS_NEWCTX, 0)`` call to submit all previous ``set_option()`` calls. Without ``OPT_X_TLS_NEWCTX``, settings are effectively ignored. 

```
        l.set_option(ldap.OPT_PROTOCOL_VERSION, ldap.VERSION3)
        l.set_option(ldap.OPT_X_TLS_CACERTFILE, 'path/to/ca.pem')
        l.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, ldap. OPT_X_TLS_NEVER)
        l.set_option(ldap.OPT_X_TLS_NEWCTX, 0)
```

**Comment by tiran** [comment]
See https://bugzilla.redhat.com/show_bug.cgi?id=1048475

**Comment by encukou** [comment]
Do we want to actually track this in code, issue a warning for one release, then make it a hard error?

**Comment by tiran** [comment]
It's a bit tricky. The cert settings can be changed globally ``ldap_set_option(NULL, opt, val)`` and locally ``ldap_set_option(conn, opt, val)``. I'm not sure how to fix cases like:

```
conn = ldap.initialize()
# now change the global setting but expect the local connection to pick up the change
ldap.set_option(ldap.OPT_X_TLS_REQUIRE_CERT, True)
conn.start_tls_s()
```

**Comment by encukou** [comment]
Documenting it is fine, or at least a good first step. We don't need to hand-hold the users (though it would be nice if we did).

**Comment by encukou** [comment]
Anyway, I don't think 3.0.0 beta needs to wait for this, as it's not a regression from either python-ldap or pyldap.

**Comment by graingert** [comment]
https://github.com/tribe29/checkmk/commit/caa7fe1c16393322bcc12b13333d48ff59eedd09

sometimes settings OPT_X_TLS_NEWCTX throws a ValueError, but it still connects successfully

This is a problem for reconnecting ldap object because it doesn't catch the value error when settings OPT_X_TLS_NEWCTX 

@LarsMichelsen
@tiran

**Comment by graingert** [comment]
@encukou would it be better if all options were set at once using a namedtuple?

```python
ldap.initialize(uri=x, options=ldap.Options(referrals=0, tls_certfile=..., ))
```

and global `set_option` was removed?

**Comment by tiran** [comment]
> [tribe29/checkmk@caa7fe1](https://github.com/tribe29/checkmk/commit/caa7fe1c16393322bcc12b13333d48ff59eedd09)
> 
> sometimes setting OPT_X_TLS_NEWCTX throws a ValueError, but it still connects successfully
> 
> This is a problem for reconnecting ldap object because it doesn't catch the value error when settings OPT_X_TLS_NEWCTX

I'm only familiar with the OpenSSL and NSS backends. I know for a fact that the OpenSSL backend throws a ValueError with ``OPT_X_TLS_NEWCTX`` when ``OPT_X_TLS_CACERTFILE`` points to an invalid or missing CA cert bundle. You might still be able to connect but not with the configuration you are expecting. It's possible that you end up with an insecure connection.

**Comment by graingert** [comment]
Would it be possible to throw a FileNotFoundError instead?

**Comment by tiran** [comment]
No, OpenLDAP libldap does not return additional information. python-ldap just gets a generic error code.

```
>>> import ldap
>>> conn = ldap.initialize("ldap://localhost")
>>> conn.set_option(ldap.OPT_X_TLS_CACERTFILE, "/invalid")
>>> conn.set_option(ldap.OPT_X_TLS_NEWCTX, 0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.7/site-packages/ldap/ldapobject.py", line 919, in set_option
    return self._ldap_call(self._l.set_option,option,invalue)
  File "/usr/lib64/python3.7/site-packages/ldap/ldapobject.py", line 313, in _ldap_call
    result = func(*args,**kwargs)
ValueError: option error
```

**Comment by graingert** [comment]
@tiran `conn.set_option(ldap.OPT_X_TLS_NEWCTX, 0)` relies on undocumented behaviour
`conn.set_option(ldap.OPT_X_TLS_NEWCTX, 1)` is preferred

**Comment by graingert** [comment]
https://www.openldap.org/its/index.cgi/Incoming?id=8805

**Comment by graingert** [comment]
@tiran I've raised an issue re the generic error code with openldap https://www.openldap.org/its/index.cgi/Incoming?id=9157

**Comment by tiran** [comment]
``conn.set_option(ldap.OPT_X_TLS_NEWCTX, 1)`` instructs OpenLDAP to create a context for an LDAP server. LDAP client libraries such as python-ldap must use ``conn.set_option(ldap.OPT_X_TLS_NEWCTX, 0)``.

**Comment by graingert** [comment]
@tiran ah yes I misunderstood that issue thread

**Comment by tiran** [comment]
Looks like I'm not the only person that got confused by OpenLDAP's documentation. :) I started https://www.openldap.org/its/index.cgi/Incoming?id=8805 because I misunderstood how NEWCTX works.

**Comment by hyc** [comment]
In OpenLDAP 2.6 (due for release in September) the fix for [ITS#9157](https://bugs.openldap.org/show_bug.cgi?id=9157) will be released. The error message from the TLS library will be saved in
the LDAP* handle and retrievable via ldap_get_option(ld, LDAP_OPT_DIAGNOSTIC_MESSAGE, ...).
