### ISSUE TITLE
Python 3 pip install broken

### ISSUE THREAD

**Issue by cccaballero** [python-ldap/python-ldap#68]
Issue description:
The installation for Python 3 using pip is broken, this is the error:

Collecting python-ldap
  Using cached python-ldap-2.5.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-tfw_257v/python-ldap/setup.py", line 9, in <module>
        from ConfigParser import ConfigParser
    ImportError: No module named 'ConfigParser'

Steps to reproduce: 
python3 -m pip install python-ldap

Operating system: 
Ubuntu 16.04

Python version: 
3.5.2

python-ldap version: 
2.5.2

**Comment by encukou** [comment]
Hi,
A version that supports Python 3 was not released yet. Stay tuned!

**Comment by spaceone** [comment]
Maybe the setup.py should include a version check and explain the situation, so that the mailing list and this issue tracker doesn't need to answer this question every day.

**Comment by encukou** [comment]
That puts me either release a 2.5.3 with a setup.py check, or hurry up with 3.0. I'm currently leaning towards the latter, with a documentation change explaining the things in the meanwhile.

**Comment by encukou** [comment]
Thanks for reporting it! I misjudged how easy it is to find the development documentation.
