### ISSUE TITLE
DeprecationWarning: 'U' mode is deprecated

### ISSUE THREAD

**Issue by tiran** [python-ldap/python-ldap#96]
virtualenv seems to ship a site.py that uses a deprecated feature. Since we turn all warnings into fatal errors, the test suite in Fedora's RPM does not pass:

```
py36 runtests: commands[0] | /home/heimes/redhat/rpms/python-ldap/python-ldap-2.5.99/python3/.tox/py36/bin/python -bb -Werror -Wignore:the imp module is deprecated:DeprecationWarning -Wignore:the imp module is deprecated:PendingDeprecationWarning -m coverage run --parallel setup.py test
Failed to import the site module
Traceback (most recent call last):
  File "/home/heimes/redhat/rpms/python-ldap/python-ldap-2.5.99/python3/.tox/py36/lib64/python3.6/site.py", line 703, in <module>
    main()
  File "/home/heimes/redhat/rpms/python-ldap/python-ldap-2.5.99/python3/.tox/py36/lib64/python3.6/site.py", line 686, in main
    paths_in_sys = virtual_addsitepackages(paths_in_sys)
  File "/home/heimes/redhat/rpms/python-ldap/python-ldap-2.5.99/python3/.tox/py36/lib64/python3.6/site.py", line 644, in virtual_addsitepackages
    return addsitepackages(known_paths, sys_prefix=sys.real_prefix)
  File "/home/heimes/redhat/rpms/python-ldap/python-ldap-2.5.99/python3/.tox/py36/lib64/python3.6/site.py", line 282, in addsitepackages
    addsitedir(sitedir, known_paths)
  File "/home/heimes/redhat/rpms/python-ldap/python-ldap-2.5.99/python3/.tox/py36/lib64/python3.6/site.py", line 204, in addsitedir
    addpackage(sitedir, name, known_paths)
  File "/home/heimes/redhat/rpms/python-ldap/python-ldap-2.5.99/python3/.tox/py36/lib64/python3.6/site.py", line 165, in addpackage
    f = open(fullname, "rU")
DeprecationWarning: 'U' mode is deprecated
```

See
* https://github.com/pypa/virtualenv/issues/555
* https://github.com/conda/conda/issues/5598

**Comment by encukou** [comment]
Probably fixed. Even if not, this is not an issue in python-ldap.
